Scene Name: Untitled
Entities:
  - EntityID: 13005225625728565025
    Tag Component:
      Tag: Face2
    Transform Component:
      Translation: [0, 0.5, 0]
      Scale: [1, 1, 1]
      Rotation: [1.57079637, 0, 0]
    Sprite Renderer Component:
      Color: [0.16364792, 0.681129158, 0.737903237, 1]
  - EntityID: 10068410578598511638
    Tag Component:
      Tag: Face1
    Transform Component:
      Translation: [0.5, 0, 0]
      Scale: [1, 1, 1]
      Rotation: [0, 1.57079637, 0]
    Sprite Renderer Component:
      Color: [0.121162832, 0.765632749, 0.834677398, 1]
  - EntityID: 17515331893798934994
    Tag Component:
      Tag: Face3
    Transform Component:
      Translation: [0, 0, 0.5]
      Scale: [1, 1, 1]
      Rotation: [0, 0, 0]
    Sprite Renderer Component:
      Color: [0.049167525, 0.528088212, 0.580645204, 1]
  - EntityID: 7608769559036410033
    Tag Component:
      Tag: Camera
    Transform Component:
      Translation: [2.80248427, 0.00295895338, -0.114405006]
      Scale: [1, 1, 1]
      Rotation: [0, 1.57079637, 0]
    Camera Component:
      Camera:
        ProjectionType: 1
        OrthographicSize: 1
        OrthographicNear: 1
        OrthographicFar: -1
        PerspectiveVerticalFOV: 0.785398185
        PerspectiveNear: 0.00100000005
        PerspectiveFar: 10000
      Primary: true
      KeepAspectRatio: false